### ISSUE TITLE
Problem with cmdPressKey() function, can't press ENTER

### ISSUE THREAD

**Issue by githubkon** [mharjac/bad_ducky#2]
There is a problem with source code, I think part with typing language, cmdPressKey function. Command "ENTER" (maybe more) is not execute in cmd. 

That for example execute well.:
  Keyboard.press(KEY_RETURN);
  delay(50);
  Keyboard.release(KEY_RETURN);

But Yours function cmdPressKey with  pressChar(convertLangChar(key)) not.

Configuration.:
Current mode: c
Current language: en
Current payload: demo1.txt

**Comment by mharjac** [comment]
Sorry for not replying you earlier. Sometimes your target host can't accept characters at the speed that ducky is "typing" them. You can slower it down by increasing delays in [printChar](https://github.com/mharjac/bad_ducky/blob/2be507741fdb829cd97acbe5688a47d1febdfaab/bad_ducky.ino#L172-L185) function. The other thing you can try is increasing delay between command execution by using DELAY or DEFAULTDELAY commands in your scripts.

**Comment by githubkon** [comment]
This solution didn't help.
