### ISSUE TITLE
How to make keymap files

### ISSUE THREAD

**Issue by florisvdk** [mharjac/bad_ducky#3]
Hi, What format do the keymap fiels use?

**Comment by mharjac** [comment]
In short, it's a binary file. First byte is character value in English keyboard layout, second is modifier (shift, alt etc.) and the third one is targeted layout value. Let's take "@" character for example. In English layout character is represented by value 0x40. In Croatian layout you have to press right alt (0x86) and "v" (0x76). I'm going to write a tutorial how to create keymap files.

![](https://res.cloudinary.com/dpkdfsocp/image/upload/v1522835953/bad_ducky_github/Screenshot_from_2018-04-04_11-54-24_os0rkb.png)

**Comment by mharjac** [comment]
I've added [how to create keymap files](https://github.com/mharjac/bad_ducky/wiki/How-to-create-keymap-files)  to the wiki. I hope this will be helpful to you...

**Comment by florisvdk** [comment]
Yes, Thank you so much. When i finish mine for Belgian layout i will make a pull request.
