### ISSUE TITLE
ENTER key doesn't work

### ISSUE THREAD

**Issue by donovanmagryta** [mharjac/bad_ducky#4]
Hi,

CTRL-SHIFT ENTER and also ENTER do nothing.

Please fix this.

Windows 10.

**Comment by Dekanser** [comment]
Hey. Try to take the file bad_ducky-master \ demo_scripts \ demo1.txt
and use it. If necessary, then edit it in notepad ++
At me all perfectly works)
win 10

**Comment by mharjac** [comment]
Just like @Dekanser wrote, this happens when you are using wrong line ending. You must use some editor which supports LF (Windows Notepad supports only CRLF)! 
[https://en.wikipedia.org/wiki/Newline](https://en.wikipedia.org/wiki/Newline)
