### ISSUE TITLE
Enable both USB HID Keyboard and USB Mass Storage?

### ISSUE THREAD

**Issue by vulnchecker** [mharjac/bad_ducky#6]
It would be nice if the bad ducky would also support USB Mass Storage like the Rubber Ducky does.

By that you would be able to write files onto the sd card while executing payloads with keystrokes.

Is there a way to integrate this?

**Comment by mharjac** [comment]
Yes, that would be a nice feature. As far as I know, you will have to write your own bootloader... Maybe LUFA framework would be helpful. Some useful links:
- http://www.fourwalledcubicle.com/LUFA.php  
- https://github.com/Palatis/Arduino-Lufa
- http://fourwalledcubicle.com/blog/2012/08/lufa-and-the-arduino-leonardo/
